// Registry for the style-theme picker (theme.js's start()/setStyle()) - mirrors
// colors/all-colors.js's {list: [...]} shape. Names/descriptions live here rather than
// language.json for now (these are design names, not strings needing translation the way
// language.settings.theme.colors's four entries are) - moving them there later is just relocating
// this one object, nothing about the token system itself depends on where the label comes from.
module.exports = {
	list: [
		'sumi-e-ink', 'tokyo-neon-alley', 'kraft-and-twine', 'aurora-observatory', 'woodblock-press',
		'terrarium', 'brass-and-velvet', 'solar-flare', 'frosted-glacier', 'deep-sea-bioluminescence',
		'letterpress-broadsheet', 'copper-circuit', 'sakura-drift', 'obsidian-forge', 'watercolor-bleed',
		'monsoon-slate', 'retro-crt-terminal', 'marble-atrium', 'autumn-ledger', 'arctic-aurora-pulse',
		'velvet-noir', 'coral-reef', 'origami-fold', 'golden-hour', 'chalkboard-study',
		'lacquer-and-jade', 'static-radio-wave', 'glacial-data-center', 'moth-light-lantern', 'risograph-print',
	],
	names: {
		'sumi-e-ink': 'Sumi-e Ink',
		'tokyo-neon-alley': 'Tokyo Neon Alley',
		'kraft-and-twine': 'Kraft & Twine',
		'aurora-observatory': 'Aurora Observatory',
		'woodblock-press': 'Woodblock Press',
		'terrarium': 'Terrarium',
		'brass-and-velvet': 'Brass & Velvet',
		'solar-flare': 'Solar Flare',
		'frosted-glacier': 'Frosted Glacier',
		'deep-sea-bioluminescence': 'Deep Sea Bioluminescence',
		'letterpress-broadsheet': 'Letterpress Broadsheet',
		'copper-circuit': 'Copper Circuit',
		'sakura-drift': 'Sakura Drift',
		'obsidian-forge': 'Obsidian Forge',
		'watercolor-bleed': 'Watercolor Bleed',
		'monsoon-slate': 'Monsoon Slate',
		'retro-crt-terminal': 'Retro CRT Terminal',
		'marble-atrium': 'Marble Atrium',
		'autumn-ledger': 'Autumn Ledger',
		'arctic-aurora-pulse': 'Arctic Aurora Pulse',
		'velvet-noir': 'Velvet Noir',
		'coral-reef': 'Coral Reef',
		'origami-fold': 'Origami Fold',
		'golden-hour': 'Golden Hour',
		'chalkboard-study': 'Chalkboard Study',
		'lacquer-and-jade': 'Lacquer & Jade',
		'static-radio-wave': 'Static Radio Wave',
		'glacial-data-center': 'Glacial Data Center',
		'moth-light-lantern': 'Moth-Light Lantern',
		'risograph-print': 'Risograph Print',
	},
	descriptions: {
		'sumi-e-ink': 'East Asian ink wash - soft brush-bleed blooms, unhurried motion.',
		'tokyo-neon-alley': 'Cyberpunk night street - sharp glass, fast mechanical snap.',
		'kraft-and-twine': 'Analog stationery/zine - typewriter face, flat matte corners.',
		'aurora-observatory': 'The default Aurora Mesh, promoted to a full style.',
		'woodblock-press': 'Folk woodblock print - thick square corners, heavy slab type.',
		'terrarium': 'Living and organic - everything rounded like a leaf edge.',
		'brass-and-velvet': 'A vintage study - ornate curves, metal-trim borders.',
		'solar-flare': 'Bold daytime energy - punchy snap, huge impact type.',
		'frosted-glacier': 'Icy minimal - thin hairlines, crisp cool motion.',
		'deep-sea-bioluminescence': 'Ocean depths - jellyfish-soft shapes, glowing pulse.',
		'letterpress-broadsheet': 'Newspaper - square corners, halftone speckle.',
		'copper-circuit': 'Steampunk-tech - small radii, etched-line grid.',
		'sakura-drift': 'Spring and soft - gentle floating-petal motion.',
		'obsidian-forge': 'Molten and volcanic - engraved type, ember glow.',
		'watercolor-bleed': 'Soft artistic - irregular ink-brush blooms, hand-drawn type.',
		'monsoon-slate': 'Moody rain - calm restrained shapes, quiet motion.',
		'retro-crt-terminal': 'Green-phosphor monochrome - square, instant, scanlined.',
		'marble-atrium': 'Gallery luxury - restrained radii, stately motion.',
		'autumn-ledger': 'A cozy fall library - warm bookish shapes.',
		'arctic-aurora-pulse': 'Colder and starker - crisp radii, aurora at the edge only.',
		'velvet-noir': 'Film-noir detective - hard edges, venetian-blind shadow.',
		'coral-reef': 'Vibrant undersea colour - fully rounded, bouncy motion.',
		'origami-fold': 'Paper-craft - crisp facets, sharp fold-snap motion.',
		'golden-hour': 'Warm cinematic sunset - soft curves, slow dissolve.',
		'chalkboard-study': 'Classroom nostalgia - chalk-drawn corners, loose motion.',
		'lacquer-and-jade': 'East Asian lacquerware - glossy restraint, jade glow.',
		'static-radio-wave': 'Analog broadcast - dial-rounded controls, amber glow.',
		'glacial-data-center': 'Cool minimal-tech - small radii, server-rack grid.',
		'moth-light-lantern': 'Warm nocturnal - lantern-soft shapes, firefly glow.',
		'risograph-print': 'Indie zine printing - bold flat shapes, riso grain.',
	},
	// Two representative colours per style, for the picker's preview swatch - the same shape
	// colors/all-colors.js already samples out of each colour tokens.css for its own preview, but
	// picked by hand here rather than parsed out of a gradient string.
	swatches: {
		'sumi-e-ink': ['#e8e4d8', '#1a1a1a'],
		'tokyo-neon-alley': ['#ff2fa1', '#38d9ff'],
		'kraft-and-twine': ['#c9a86b', '#3a2e1c'],
		'aurora-observatory': ['#7c4dff', '#2dd4bf'],
		'woodblock-press': ['#e9e1cd', '#b8291e'],
		'terrarium': ['#4caf64', '#8d6e46'],
		'brass-and-velvet': ['#8c283c', '#c8961e'],
		'solar-flare': ['#ff9400', '#ff5722'],
		'frosted-glacier': ['#d2ebff', '#a7c9de'],
		'deep-sea-bioluminescence': ['#2dd4bf', '#9650ff'],
		'letterpress-broadsheet': ['#efe6d2', '#1e1c18'],
		'copper-circuit': ['#c8823c', '#3a2c1a'],
		'sakura-drift': ['#ffb7c5', '#ffd6e0'],
		'obsidian-forge': ['#1a1a1a', '#ff6e1e'],
		'watercolor-bleed': ['#5a82c8', '#c86e82'],
		'monsoon-slate': ['#7c8ea6', '#3a4552'],
		'retro-crt-terminal': ['#0a0a0a', '#3cff82'],
		'marble-atrium': ['#e8e4da', '#b8ad98'],
		'autumn-ledger': ['#c86e28', '#8a5a28'],
		'arctic-aurora-pulse': ['#78dcb4', '#9678e6'],
		'velvet-noir': ['#0a0a0a', '#a3181c'],
		'coral-reef': ['#2dd4bf', '#ff8a65'],
		'origami-fold': ['#e8e8e8', '#b0b0b0'],
		'golden-hour': ['#ff8c3c', '#ff6482'],
		'chalkboard-study': ['#1e3a2e', '#f0f0f0'],
		'lacquer-and-jade': ['#0a0a0a', '#46c896'],
		'static-radio-wave': ['#3a2410', '#ffb43c'],
		'glacial-data-center': ['#eef4fa', '#78c8ff'],
		'moth-light-lantern': ['#1a1830', '#ffc85a'],
		'risograph-print': ['#ff5a8c', '#3caaff'],
	},
};
